### ISSUE TITLE
I need commit access to this repo

### ISSUE THREAD

**Issue by peterbe** [mozilla-l10n/mdn-l10n#6]
I'm working on `kuma-deployer` to push to this repo. For that I need commit access. 

@escattone This is blocking me from finishing the locale refresh thing in `kuma-deployer`.

**Comment by flodolo** [comment]
Sent you an invite

**Comment by peterbe** [comment]
[Seems to have worked wonderfully](https://github.com/mozilla-l10n/mdn-l10n/commit/54e3801cbc22f49def70bcea93261ed20bf6669d)
Thanks!
